config/routes.rb
Wanerbu::Application.routes.draw do

  get "gym/gym_home"
  match 'gym/search/:sportid/:areaid/:keyword/:reservekey/:sortkey' => 'gym#search',:via=>:get
  match 'gym/one_gym/:id/:sportid' => 'gym#one_gym',:via=>:get
  match 'gym/submit_comment' => 'gym#submit_comment',:via => :post
  match 'gym/search_comment/:gymid' => 'gym#search_comment',:via=>:get
  match 'gym/delete_comment/:gymid/:commentid' => 'gym#delete_comment',:via=>:get
  match 'gym/check_comment_time' => 'gym#check_comment_time',:via => :post
  match 'gym/getcourt/:gymid/:sportid/:reservationtype' => 'gym#getcourt',:via=>:get
  match 'gym/reserve/:id/:date' => 'gym#reserve',:via=>:get
  match 'gym/searchgame/:id/:date' => 'gym#searchgame',:via=>:get
  match 'gym/check_order' => 'gym#check_order',:via => :post
  match 'gym/check_code_image/:type_code' => 'gym#check_code_image',:via => :get
  match 'gym/submit_order' => 'gym#submit_order',:via => :post
  match 'gym/search_map' => 'gym#search_map',:via => :post
  match 'gym/code_image' => 'gym#code_image',:via => :get

  get "activities/activity_home"
  get "activities/search/:id/:type" => 'activities#search',:via=>:get
  match 'activities/get_cities_by_province_id/:province_id' => 'activities#get_cities_by_province_id',:via=>:get
  match 'activities/get_areas_by_city_id/:city_id' => 'activities#get_areas_by_city_id',:via=>:get
  resources :activities, :except => [:index] 

  devise_for :users,
    :controllers => {:sessions => 'user/users/sessions', :registrations => 'user/users/registrations'},
    :path => 'auth',
    :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  devise_for :admins,
    :controllers => {:sessions => 'admin/admins/sessions'},
    :path => 'admin/auth',
    :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  root :to => 'welcome#index'

  namespace :admin do
    root :to => 'dashboard#index'
    get 'dashboard' => 'dashboard#index'
    namespace :master do
      resources :admins, :except => [:index] do
        member do
          post :lock
        end
      end
      resources :admin_reports, :only => [:index]
      resources :roles, :except => [:index]
      resources :role_reports, :only => [:index]
      resources :properties, :except => [:index]
      resources :property_reports, :only => [:index]
      resources :sports, :except => [:index]
      resources :sport_reports, :only => [:index]
      resources :gym_reports, :only => [:index,:show] do
        member do
          post :approve
          post :reject
          post :lock
          post :destroy
        end
      end
    end
  end

  namespace :user do
    root :to => 'dashboard#index'
    get 'dashboard' => 'dashboard#index'
    namespace :master do
      resources :gyms do
        member do
          post :apply
          post :cancel
          post :release
          post :suspend
        end
      end
      match 'gyms/upload_image' => 'gyms#upload_image',:via => :post
      match 'gyms/remove_image' => 'gyms#remove_image',:via => :post
      match 'gyms/get_cities_by_province_id/:province_id' => 'gyms#get_cities_by_province_id',:via=>:get
      match 'gyms/:id/get_cities_by_province_id/:province_id' => 'gyms#get_cities_by_province_id',:via=>:get
      match 'gyms/get_areas_by_city_id/:city_id' => 'gyms#get_areas_by_city_id',:via=>:get
      match 'gyms/:id/get_areas_by_city_id/:city_id' => 'gyms#get_areas_by_city_id',:via=>:get
      resources :courts, :except => [:index]
      resources :court_reports, :only => [:index]
      match 'courts/edit_court_properties_select/:sport_id' => 'courts#edit_court_properties_select',:via=>:get
      match 'courts/:id/edit_court_properties_select/:sport_id' => 'courts#edit_court_properties_select',:via=>:get
      resources :games, :except => [:index] do
        member do
          post :new_price_rule
          post :new_reservation_rule
        end
      end
      match 'games/delete_game_price_rule/:price_rule_id' => 'games#delete_game_price_rule',:via=>:get
      match 'games/delete_game_reservation_rule/:reservation_rule_id' => 'games#delete_game_reservation_rule',:via=>:get
      resources :game_reports, :only => [:index]
    end
  end

end

app/controllers/admin/master/admin_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: dairugang
#
#++
#
class Admin::Master::AdminReportsController < Admin::AdminBaseController

  # 对于每一个action进行权限检查
  load_and_authorize_resource 

  def index
    @admin_report = AdminReport.new(params[:admin_report])
    @admin_report.assets.per_page = Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @admin_report.assets.page(params[:page])
  end
end

app/controllers/admin/master/admins_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: dairugang
#
#++
#
class Admin::Master::AdminsController < Admin::AdminBaseController

  # 对于每一个action进行权限检查
  load_and_authorize_resource 

  def show
    @admin = Admin.find(params[:id])
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params[:admin])
    if @admin.save
      # 发送包含自动生成密码的欢迎邮件
      Admin::WanerbuDeviseMailer.welcome_admin(@admin).deliver
      redirect_to admin_master_admin_path(@admin), notice: I18n.t("activemodel.success.create", model: Admin.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.create", model: Admin.model_name.human)
      render :new
    end
  end

  def edit
    @admin = Admin.find(params[:id])

    return unless only_super_admin_validate?

  end

  # 
  def update
    @admin = Admin.find(params[:id])
    # TODO dairg 存在性的check
 
    return unless only_super_admin_validate?

    if @admin.update_attributes(params[:admin])
      redirect_to admin_master_admin_path(@admin), notice: I18n.t("activemodel.success.update", model: Admin.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.update", model: Admin.model_name.human)
      render :edit
    end
  end

  def destroy
    @admin = Admin.find(params[:id])
    # TODO dairg 存在性的check

    return unless only_super_admin_validate?
    if @admin.destroy
      redirect_to admin_master_admin_reports_path, notice: I18n.t("activemodel.success.destroy", model: Admin.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Admin.model_name.human)
      render :show
    end
  end

  # 锁定
  def lock
    @admin = Admin.find(params[:id])
    # TODO dairg 存在性的check
 
    # 如果操作对象是唯一的超级管理员，不能进行该操作
    return unless only_super_admin_validate?

    if @admin.update_attribute(:status, Wanerbu::CodeDefine::ADMIN_STATUS[:locked])
      redirect_to admin_master_admin_path(@admin), notice: I18n.t("activemodel.success.lock", model: Admin.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.lock", model: Admin.model_name.human)
      render :show
    end
  end

private
  def only_super_admin_validate?
    if @admin.only_super_admin?
      render File.join(Rails.root, 'public', '403'), formats: [:html], status: 403, layout: false
      return false
    end
    return true
  end
end

app/controllers/admin/master/gym_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class Admin::Master::GymReportsController < Admin::AdminBaseController

  def index
    @gym_report = GymReport.new(params[:gym_report])
    @gym_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @gym_report.assets.page(params[:page])
  end

  def show
    @gym= Gym.find(params[:id])
  end
  # 同意
  def approve
    @gym = Gym.find(params[:id])
    approve_history_log = generate_log("approve")
    if @gym.update_attribute(:status, Wanerbu::CodeDefine::GYM_STATUS[:approved]) && @gym.update_attribute(:history_log, approve_history_log)
      redirect_to admin_master_gym_report_path(@gym), notice: I18n.t("activemodel.success.approve", model: Gym.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.approve", model: Gym.model_name.human)
      render :show
    end
  end
  # 拒绝
  def reject
    @gym = Gym.find(params[:id])
    reject_history_log = generate_log("reject")
    if @gym.update_attribute(:status, Wanerbu::CodeDefine::GYM_STATUS[:rejected]) && @gym.update_attribute(:history_log, reject_history_log) && @gym.update_attribute(:reason, params[:reason])
      redirect_to admin_master_gym_report_path(@gym), notice: I18n.t("activemodel.success.reject", model: Gym.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.reject", model: Gym.model_name.human)
      render :show
    end
  end
  # 锁定
  def lock
    @gym = Gym.find(params[:id])
    lock_history_log = generate_log("lock")
    if @gym.update_attribute(:status, Wanerbu::CodeDefine::GYM_STATUS[:locked]) && @gym.update_attribute(:history_log, lock_history_log) && @gym.update_attribute(:reason, params[:reason])
      redirect_to admin_master_gym_report_path(@gym), notice: I18n.t("activemodel.success.lock", model: Gym.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.lock", model: Gym.model_name.human)
      render :show
    end
  end
  def destroy
    # TODO Tom 存在性的check
    @gym = Gym.find(params[:id])
    if @gym.destroy
      redirect_to admin_master_gym_reports_path, notice: I18n.t("activemodel.success.destroy", model: Gym.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Gym.model_name.human)
      render :show
    end
  end
  #生成历史记录
  def generate_log(action)
    if @gym.history_log.nil?
        action_history_log = current_admin.login_id + "于"+ Time.now.to_date.to_s + " " + Time.now.strftime("%H:%M").to_s + I18n.t("activemodel.success."+action, model: Gym.model_name.human)  + ";"
    else
        action_history_log = @gym.history_log + current_admin.login_id + "于"+ Time.now.to_date.to_s + " " + Time.now.strftime("%H:%M").to_s + I18n.t("activemodel.success."+action, model: Gym.model_name.human)  + ";"
    end
    return action_history_log
  end
end

app/controllers/admin/master/properties_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
class Admin::Master::PropertiesController < Admin::AdminBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  def show
    @property = Property.find(params[:id])
  end
  def new
    @property = Property.new
  end
  def create
    @property = Property.new(params[:property])
    if @property.save
      redirect_to admin_master_property_path(@property), notice: I18n.t("activemodel.success.create", model: Property.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.create", model: Property.model_name.human)
      render :new
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    # TODO Tom 存在性的check
    if @property.update_attributes(params[:property])
      redirect_to admin_master_property_path(@property), notice: I18n.t("activemodel.success.update", model: Property.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.update", model: Property.model_name.human)
      render :edit
    end
  end
  def destroy
    @property = Property.find(params[:id])
    # TODO Tom  存在性的check

    if @property.destroy
      redirect_to new_admin_master_property_path, notice: I18n.t("activemodel.success.destroy", model: Property.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Property.model_name.human)
      render :show
    end
  end
end

app/controllers/admin/master/property_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class Admin::Master::PropertyReportsController < Admin::AdminBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  def index
    @property_report = PropertyReport.new(params[:property_report])
    @property_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE 
    @assets = @property_report.assets.page(params[:page])
  end
end

app/controllers/admin/master/role_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: dairugang
#
#++
#
class Admin::Master::RoleReportsController < Admin::AdminBaseController

  # 对于每一个action进行权限检查
  load_and_authorize_resource 

  def index
    @role_report = RoleReport.new(params[:role_report])
    @role_report.assets.per_page = Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @role_report.assets.page(params[:page])
  end
end

app/controllers/admin/master/roles_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: dairugang
#
#++
#
class Admin::Master::RolesController < Admin::AdminBaseController

  # 对于每一个action进行权限检查
  load_and_authorize_resource 

  def show
    @role = Role.find(params[:id])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(params[:role])
    if @role.save
      redirect_to admin_master_role_path(@role), notice: I18n.t("activemodel.success.create", model: Role.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.create", model: Role.model_name.human)
      render :new
    end
  end

  def edit
    @role = Role.find(params[:id])
  end

  # 
  def update
    @role = Role.find(params[:id])
    # TODO dairg 存在性的check
    if @role.update_attributes(params[:role])
      redirect_to admin_master_role_path(@role), notice: I18n.t("activemodel.success.update", model: Role.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.update", model: Role.model_name.human)
      render :edit
    end
  end

  def destroy
    @role = Role.find(params[:id])
    # TODO dairg 存在性的check

    if @role.destroy
      redirect_to admin_master_role_reports_path, notice: I18n.t("activemodel.success.destroy", model: Role.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Role.model_name.human)
      render :show
    end
  end
end

app/controllers/admin/master/sport_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class Admin::Master::SportReportsController < Admin::AdminBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  def index
    @sport_report = SportReport.new(params[:sport_report])
    @sport_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @sport_report.assets.page(params[:page])
  end
end

app/controllers/admin/master/sports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
class Admin::Master::SportsController < Admin::AdminBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  def show
    @sport = Sport.find(params[:id])
  end
  def new
    @sport = Sport.new
  end
  def create
    @sport = Sport.new(params[:sport])
    if @sport.save
      redirect_to admin_master_sport_path(@sport), notice: I18n.t("activemodel.success.create", model: Sport.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.create", model: Sport.model_name.human)
      render :new
    end
  end

  def edit
    @sport = Sport.find(params[:id])
  end

  def update
    @sport = Sport.find(params[:id])
    if params[:sport][:sport_properties_attributes].present?
      params[:sport][:sport_properties_attributes].each do |p|
        p[:_destroy] = true if p[:property_id].blank?
      end
    end
    # TODO Tom 存在性的check
    if @sport.update_attributes(params[:sport])
      redirect_to admin_master_sport_path(@sport), notice: I18n.t("activemodel.success.update", model: Sport.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.update", model: Sport.model_name.human)
      render :edit
    end
  end
  def destroy
    @sport = Sport.find(params[:id])
    # TODO Tom  存在性的check

    if @sport.destroy
      redirect_to new_admin_master_sport_path, notice: I18n.t("activemodel.success.destroy", model: Sport.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Sport.model_name.human)
      render :show
    end
  end
end

app/controllers/user/master/court_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class User::Master::CourtReportsController < User::UserBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  before_filter :set_current_user
  def index
    @court_report = CourtReport.new(params[:court_report])
    @court_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @court_report.assets.page(params[:page])
  end
end

app/controllers/user/master/game_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class User::Master::GameReportsController < User::UserBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  before_filter :set_current_user
  def index
    @game_report = GameReport.new(params[:game_report])
    @game_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @game_report.assets.page(params[:page])
  end
end

app/helpers/admin/master/admin_reports_helper.rb
module Admin::Master::AdminReportsHelper
end

app/helpers/admin/master/admins_helper.rb
module Admin::Master::AdminsHelper
end

app/helpers/admin/master/gym_reports_helper.rb
module Admin::Master::GymReportsHelper
end

app/helpers/admin/master/properties_helper.rb
module Admin::Master::PropertiesHelper
end

app/helpers/admin/master/property_reports_helper.rb
module Admin::Master::PropertyReportsHelper
end

app/views/user/master/courts/_form.html.erb
<%= javascript_include_tag "user/master/courts.js" %>
<%= semantic_form_for([:user, :master, @court], :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.inputs :name => t('views.defaults.label.base_info') do %>
    <!--新建-->
    <% if @court.new_record? %>
      <%#= f.input :sport_id, :label => Sport.model_name.human, :required => true, :as => :select,:collection => Sport.all,:selected => Sport.first.id %>
      <li id="court_sport_id_input" class="select input required">
      <label class=" label" for="court_sport_id">
        <%= Sport.model_name.human %><abbr title="required">*</abbr>
      </label>
      <%= collection_select(:court, :sport_id, Sport.all, :id, :name) %>
      </li>
      <%= f.input :reservation_type, :as => :radio %>
      <!--异步请求返回所选项目的属性显示层-->
      <div id="courtProperties">
      </div>  
      <!--编辑-->
    <% else %>
      <li id="court_sport_name" class="number input optional numeric stringish">
      <label class=" label" for="court_sport_name"><%=Sport.model_name.human%></label>
      <%= Sport.find(@court.sport_id).name %>
      </li>
      <li id="court_sport_name" class="number input optional numeric stringish">
      <label class=" label" for="reservation_type"><%= Court.human_attribute_name(:reservation_type) %></label>
      <%= @court.reservation_type.text -%>
      </li>
      <div id="courtPropertiesIfEdit">
        <% @court.court_properties.all.each do |court_property| %>
          <% property = Property.find(court_property.property_id) %>
          <div>
            <%= hidden_field_tag 'court[court_properties_attributes][][id]',court_property.id %>
            <%= hidden_field_tag 'court[court_properties_attributes][][property_id]',property.id %>
            <li id="court_sport_name" class="number input optional numeric stringish">
            <label class=" label" for="court_sport_name">
              <%= label_tag :property_ids, property.name -%>
            </label>
            <%= text_field_tag 'court[court_properties_attributes][][property_value]',court_property.property_value %>
            <%= property.unit -%>
            </li>
          </div>
        <%end%>
      </div>  
    <% end %>
    <%= f.input :min_unit %>
  <% end %>
  <% if @court.new_record? %>
    <%= f.inputs :name => t('views.defaults.label.batch_game_info') do %>
      <li id="court_game_number" class="number input optional numeric stringish">
      <label class=" label" for="court_game_number"><%= t('views.defaults.game.game_number')%>
      </label>
      <%= text_field_tag 'game_number',1 %>
      </li>
      <li id="court_game_price" class="number input optional numeric stringish">
      <label class=" label" for="court_game_price"><%= Game.human_attribute_name(:default_price) %></label>
      <%= text_field_tag 'game_default_price',1 %>
      </li>
      <li id="court_game_can_reservation" class="number input optional numeric stringish">
      <label class=" label" for="court_game_can_reservation"><%= Game.human_attribute_name(:can_reservation) %></label>
      <ol class="choices-group">
        <li class="choice">
        <label for="court_game_can_reservation_true">
          <%= radio_button_tag("can_reservation_in_court", true,true) %><%= t('views.defaults.game.reservation_true')%>
        </label>
        </li>
        <li class="choice">
        <label for="court_game_can_reservation_false">
          <%= radio_button_tag("can_reservation_in_court", false) %><%= t('views.defaults.game.reservation_false')%>
        </label>
        </li>
      </ol>
      </li>
    <% end %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :button_html => { :class => "btn btn-primary" }, :as => :button %>
    <%= f.action :cancel, :as => :link %>
  <% end -%>
<% end %>

app/views/user/master/courts/_properties.html.erb
<% if !sport_properties.blank? %>
  <% sport_properties.all.each do |sport_property| %>
    <% property = Property.find(sport_property.property_id) %>
      <%= hidden_field_tag 'court[court_properties_attributes][][property_id]',property.id %>
    <li id="sport_property_name" class="number input optional numeric stringish">
      <label class=" label" for="sport_property_name">
        <%= label_tag :property_ids, property.name -%>
      </label>
      <%= text_field_tag 'court[court_properties_attributes][][property_value]',sport_property.default_value %>
      <%= property.unit -%>
    </li>
  <%end%>
<% else %>
<% end %>

app/views/user/master/courts/_sub_menu_start.html.erb
  <ul class="nav nav-tabs">
    <li class="<%= 'active' if active_path.present? && active_path == user_master_court_reports_path %>">
      <%= link_to t('user.nav.main_menu.common.list', model: Court.model_name.human), user_master_court_reports_path %>
    </li>
    <li class="<%= 'active' if active_path.present? && active_path == new_user_master_court_path %>">
      <%= link_to t('user.nav.main_menu.common.new', model: Court.model_name.human), new_user_master_court_path %>
    </li>

app/views/user/master/courts/edit.html.erb
<% content_for :sub_menu do %>
  <%= render :partial => 'user/master/courts/sub_menu_start', :locals => {:active_path => nil } -%>
    <li class="active">
      <%= link_to t('user.nav.main_menu.common.edit', model: Court.model_name.human), edit_user_master_court_path(@court) %>
    </li>
  <%= render 'common_parts/sub_menu_end' -%>
<% end %>

<div class='wb-content-main'>
  <%= render 'form' -%>
</div>

app/views/user/master/courts/new.html.erb
<% content_for :sub_menu do %>
  <%= render :partial => 'user/master/courts/sub_menu_start', :locals => {:active_path => new_user_master_court_path } -%>
  <%= render 'common_parts/sub_menu_end' -%>
<% end %>

<div class='wb-content-main'>
  <%= render 'form' -%>
</div>

app/views/user/master/courts/show.html.erb
<% content_for :sub_menu do %>
  <%= render :partial => 'user/master/courts/sub_menu_start', :locals => {:active_path => nil } -%>
    <li class="active">
      <%= link_to t('user.nav.main_menu.common.show', model: Court.model_name.human), user_master_court_path(@court) %>
    </li>
  <%= render 'common_parts/sub_menu_end' -%>
<% end %>

<div class='wb-content-sub-title'>
  <div>
    <%= link_to t('views.defaults.actions.edit'), edit_user_master_court_path(@court), {class: "btn btn-primary"} %>
    <%= link_to t('views.defaults.actions.destroy'), user_master_court_path(@court), 
                { method: :delete, class: "btn btn-primary", confirm: t('activemodel.confirm.destroy') } %>
  </div>
  <div class='wb-clear-both'></div>
</div>

<div class="wb-content-detail">
  <table class="table table-bordered" style="width: 100%;">
    <tbody>
      <tr>
        <td><%=Sport.model_name.human%></td>
        <td><%= Sport.find(@court.sport_id).name -%></td>
      </tr>
      <tr>
        <td><%= Court.human_attribute_name(:reservation_type) %></td>
        <td><%= @court.reservation_type.text -%></td>
      </tr>
      <tr>
        <td><%=Property.model_name.human%></td>
        <td>
            <% @court.court_properties.each do |court_property| -%>
            <div>
              <% property = Property.find(court_property.property_id) -%>
              <%= property.name-%>:
              <%= court_property.property_value-%>
              <%= property.unit-%>
             </div>
           <% end -%>
         </td>
       </tr>
      <tr>
        <td><%= Court.human_attribute_name(:min_unit) %></td>
        <td><%= @court.min_unit -%></td>
      </tr>
      <tr>
        <td><%= t('views.defaults.game.game_number')%>
        </td>
        <td><%= Game.where(:court_id => @court.id).count %></td>
      </tr>
    </tbody>
  </table>
</div>