config/routes.rb
Wanerbu::Application.routes.draw do

  get "gym/gym_home"
  match 'gym/search/:sportid/:areaid/:keyword/:reservekey/:sortkey' => 'gym#search',:via=>:get
  match 'gym/one_gym/:id/:sportid' => 'gym#one_gym',:via=>:get
  match 'gym/submit_comment' => 'gym#submit_comment',:via => :post
  match 'gym/search_comment/:gymid' => 'gym#search_comment',:via=>:get
  match 'gym/delete_comment/:gymid/:commentid' => 'gym#delete_comment',:via=>:get
  match 'gym/check_comment_time' => 'gym#check_comment_time',:via => :post
  match 'gym/getcourt/:gymid/:sportid/:reservationtype' => 'gym#getcourt',:via=>:get
  match 'gym/reserve/:id/:date' => 'gym#reserve',:via=>:get
  match 'gym/searchgame/:id/:date' => 'gym#searchgame',:via=>:get
  match 'gym/check_order' => 'gym#check_order',:via => :post
  match 'gym/check_code_image/:type_code' => 'gym#check_code_image',:via => :get
  match 'gym/submit_order' => 'gym#submit_order',:via => :post
  match 'gym/search_map' => 'gym#search_map',:via => :post
  match 'gym/code_image' => 'gym#code_image',:via => :get

  get "activities/activity_home"
  get "activities/search/:id/:type" => 'activities#search',:via=>:get
  match 'activities/get_cities_by_province_id/:province_id' => 'activities#get_cities_by_province_id',:via=>:get
  match 'activities/get_areas_by_city_id/:city_id' => 'activities#get_areas_by_city_id',:via=>:get
  resources :activities, :except => [:index] 

  devise_for :users,
    :controllers => {:sessions => 'user/users/sessions', :registrations => 'user/users/registrations'},
    :path => 'auth',
    :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  devise_for :admins,
    :controllers => {:sessions => 'admin/admins/sessions'},
    :path => 'admin/auth',
    :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  root :to => 'welcome#index'

  namespace :admin do
    root :to => 'dashboard#index'
    get 'dashboard' => 'dashboard#index'
    namespace :master do
      resources :admins, :except => [:index] do
        member do
          post :lock
        end
      end
      resources :admin_reports, :only => [:index]
      resources :roles, :except => [:index]
      resources :role_reports, :only => [:index]
      resources :properties, :except => [:index]
      resources :property_reports, :only => [:index]
      resources :sports, :except => [:index]
      resources :sport_reports, :only => [:index]
      resources :gym_reports, :only => [:index,:show] do
        member do
          post :approve
          post :reject
          post :lock
          post :destroy
        end
      end
    end
  end

  namespace :user do
    root :to => 'dashboard#index'
    get 'dashboard' => 'dashboard#index'
    namespace :master do
      resources :gyms do
        member do
          post :apply
          post :cancel
          post :release
          post :suspend
        end
      end
      match 'gyms/upload_image' => 'gyms#upload_image',:via => :post
      match 'gyms/remove_image' => 'gyms#remove_image',:via => :post
      match 'gyms/get_cities_by_province_id/:province_id' => 'gyms#get_cities_by_province_id',:via=>:get
      match 'gyms/:id/get_cities_by_province_id/:province_id' => 'gyms#get_cities_by_province_id',:via=>:get
      match 'gyms/get_areas_by_city_id/:city_id' => 'gyms#get_areas_by_city_id',:via=>:get
      match 'gyms/:id/get_areas_by_city_id/:city_id' => 'gyms#get_areas_by_city_id',:via=>:get
      resources :courts, :except => [:index]
      resources :court_reports, :only => [:index]
      match 'courts/edit_court_properties_select/:sport_id' => 'courts#edit_court_properties_select',:via=>:get
      match 'courts/:id/edit_court_properties_select/:sport_id' => 'courts#edit_court_properties_select',:via=>:get
      resources :games, :except => [:index] do
        member do
          post :new_price_rule
          post :new_reservation_rule
        end
      end
      match 'games/delete_game_price_rule/:price_rule_id' => 'games#delete_game_price_rule',:via=>:get
      match 'games/delete_game_reservation_rule/:reservation_rule_id' => 'games#delete_game_reservation_rule',:via=>:get
      resources :game_reports, :only => [:index]
    end
  end

end

app/controllers/admin/master/admin_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: dairugang
#
#++
#
class Admin::Master::AdminReportsController < Admin::AdminBaseController

  # 对于每一个action进行权限检查
  load_and_authorize_resource 

  def index
    @admin_report = AdminReport.new(params[:admin_report])
    @admin_report.assets.per_page = Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @admin_report.assets.page(params[:page])
  end
end

app/controllers/admin/master/admins_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: dairugang
#
#++
#
class Admin::Master::AdminsController < Admin::AdminBaseController

  # 对于每一个action进行权限检查
  load_and_authorize_resource 

  def show
    @admin = Admin.find(params[:id])
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params[:admin])
    if @admin.save
      # 发送包含自动生成密码的欢迎邮件
      Admin::WanerbuDeviseMailer.welcome_admin(@admin).deliver
      redirect_to admin_master_admin_path(@admin), notice: I18n.t("activemodel.success.create", model: Admin.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.create", model: Admin.model_name.human)
      render :new
    end
  end

  def edit
    @admin = Admin.find(params[:id])

    return unless only_super_admin_validate?

  end

  # 
  def update
    @admin = Admin.find(params[:id])
    # TODO dairg 存在性的check
 
    return unless only_super_admin_validate?

    if @admin.update_attributes(params[:admin])
      redirect_to admin_master_admin_path(@admin), notice: I18n.t("activemodel.success.update", model: Admin.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.update", model: Admin.model_name.human)
      render :edit
    end
  end

  def destroy
    @admin = Admin.find(params[:id])
    # TODO dairg 存在性的check

    return unless only_super_admin_validate?
    if @admin.destroy
      redirect_to admin_master_admin_reports_path, notice: I18n.t("activemodel.success.destroy", model: Admin.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Admin.model_name.human)
      render :show
    end
  end

  # 锁定
  def lock
    @admin = Admin.find(params[:id])
    # TODO dairg 存在性的check
 
    # 如果操作对象是唯一的超级管理员，不能进行该操作
    return unless only_super_admin_validate?

    if @admin.update_attribute(:status, Wanerbu::CodeDefine::ADMIN_STATUS[:locked])
      redirect_to admin_master_admin_path(@admin), notice: I18n.t("activemodel.success.lock", model: Admin.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.lock", model: Admin.model_name.human)
      render :show
    end
  end

private
  def only_super_admin_validate?
    if @admin.only_super_admin?
      render File.join(Rails.root, 'public', '403'), formats: [:html], status: 403, layout: false
      return false
    end
    return true
  end
end

app/controllers/admin/master/gym_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class Admin::Master::GymReportsController < Admin::AdminBaseController

  def index
    @gym_report = GymReport.new(params[:gym_report])
    @gym_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @gym_report.assets.page(params[:page])
  end

  def show
    @gym= Gym.find(params[:id])
  end
  # 同意
  def approve
    @gym = Gym.find(params[:id])
    approve_history_log = generate_log("approve")
    if @gym.update_attribute(:status, Wanerbu::CodeDefine::GYM_STATUS[:approved]) && @gym.update_attribute(:history_log, approve_history_log)
      redirect_to admin_master_gym_report_path(@gym), notice: I18n.t("activemodel.success.approve", model: Gym.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.approve", model: Gym.model_name.human)
      render :show
    end
  end
  # 拒绝
  def reject
    @gym = Gym.find(params[:id])
    reject_history_log = generate_log("reject")
    if @gym.update_attribute(:status, Wanerbu::CodeDefine::GYM_STATUS[:rejected]) && @gym.update_attribute(:history_log, reject_history_log) && @gym.update_attribute(:reason, params[:reason])
      redirect_to admin_master_gym_report_path(@gym), notice: I18n.t("activemodel.success.reject", model: Gym.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.reject", model: Gym.model_name.human)
      render :show
    end
  end
  # 锁定
  def lock
    @gym = Gym.find(params[:id])
    lock_history_log = generate_log("lock")
    if @gym.update_attribute(:status, Wanerbu::CodeDefine::GYM_STATUS[:locked]) && @gym.update_attribute(:history_log, lock_history_log) && @gym.update_attribute(:reason, params[:reason])
      redirect_to admin_master_gym_report_path(@gym), notice: I18n.t("activemodel.success.lock", model: Gym.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.lock", model: Gym.model_name.human)
      render :show
    end
  end
  def destroy
    # TODO Tom 存在性的check
    @gym = Gym.find(params[:id])
    if @gym.destroy
      redirect_to admin_master_gym_reports_path, notice: I18n.t("activemodel.success.destroy", model: Gym.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Gym.model_name.human)
      render :show
    end
  end
  #生成历史记录
  def generate_log(action)
    if @gym.history_log.nil?
        action_history_log = current_admin.login_id + "于"+ Time.now.to_date.to_s + " " + Time.now.strftime("%H:%M").to_s + I18n.t("activemodel.success."+action, model: Gym.model_name.human)  + ";"
    else
        action_history_log = @gym.history_log + current_admin.login_id + "于"+ Time.now.to_date.to_s + " " + Time.now.strftime("%H:%M").to_s + I18n.t("activemodel.success."+action, model: Gym.model_name.human)  + ";"
    end
    return action_history_log
  end
end

app/controllers/admin/master/properties_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
class Admin::Master::PropertiesController < Admin::AdminBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  def show
    @property = Property.find(params[:id])
  end
  def new
    @property = Property.new
  end
  def create
    @property = Property.new(params[:property])
    if @property.save
      redirect_to admin_master_property_path(@property), notice: I18n.t("activemodel.success.create", model: Property.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.create", model: Property.model_name.human)
      render :new
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    # TODO Tom 存在性的check
    if @property.update_attributes(params[:property])
      redirect_to admin_master_property_path(@property), notice: I18n.t("activemodel.success.update", model: Property.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.update", model: Property.model_name.human)
      render :edit
    end
  end
  def destroy
    @property = Property.find(params[:id])
    # TODO Tom  存在性的check

    if @property.destroy
      redirect_to new_admin_master_property_path, notice: I18n.t("activemodel.success.destroy", model: Property.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Property.model_name.human)
      render :show
    end
  end
end

app/controllers/admin/master/property_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class Admin::Master::PropertyReportsController < Admin::AdminBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  def index
    @property_report = PropertyReport.new(params[:property_report])
    @property_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE 
    @assets = @property_report.assets.page(params[:page])
  end
end

app/controllers/admin/master/role_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: dairugang
#
#++
#
class Admin::Master::RoleReportsController < Admin::AdminBaseController

  # 对于每一个action进行权限检查
  load_and_authorize_resource 

  def index
    @role_report = RoleReport.new(params[:role_report])
    @role_report.assets.per_page = Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @role_report.assets.page(params[:page])
  end
end

app/controllers/admin/master/roles_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: dairugang
#
#++
#
class Admin::Master::RolesController < Admin::AdminBaseController

  # 对于每一个action进行权限检查
  load_and_authorize_resource 

  def show
    @role = Role.find(params[:id])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(params[:role])
    if @role.save
      redirect_to admin_master_role_path(@role), notice: I18n.t("activemodel.success.create", model: Role.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.create", model: Role.model_name.human)
      render :new
    end
  end

  def edit
    @role = Role.find(params[:id])
  end

  # 
  def update
    @role = Role.find(params[:id])
    # TODO dairg 存在性的check
    if @role.update_attributes(params[:role])
      redirect_to admin_master_role_path(@role), notice: I18n.t("activemodel.success.update", model: Role.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.update", model: Role.model_name.human)
      render :edit
    end
  end

  def destroy
    @role = Role.find(params[:id])
    # TODO dairg 存在性的check

    if @role.destroy
      redirect_to admin_master_role_reports_path, notice: I18n.t("activemodel.success.destroy", model: Role.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Role.model_name.human)
      render :show
    end
  end
end

app/controllers/admin/master/sport_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class Admin::Master::SportReportsController < Admin::AdminBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  def index
    @sport_report = SportReport.new(params[:sport_report])
    @sport_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @sport_report.assets.page(params[:page])
  end
end

app/controllers/admin/master/sports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
class Admin::Master::SportsController < Admin::AdminBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  def show
    @sport = Sport.find(params[:id])
  end
  def new
    @sport = Sport.new
  end
  def create
    @sport = Sport.new(params[:sport])
    if @sport.save
      redirect_to admin_master_sport_path(@sport), notice: I18n.t("activemodel.success.create", model: Sport.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.create", model: Sport.model_name.human)
      render :new
    end
  end

  def edit
    @sport = Sport.find(params[:id])
  end

  def update
    @sport = Sport.find(params[:id])
    if params[:sport][:sport_properties_attributes].present?
      params[:sport][:sport_properties_attributes].each do |p|
        p[:_destroy] = true if p[:property_id].blank?
      end
    end
    # TODO Tom 存在性的check
    if @sport.update_attributes(params[:sport])
      redirect_to admin_master_sport_path(@sport), notice: I18n.t("activemodel.success.update", model: Sport.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.update", model: Sport.model_name.human)
      render :edit
    end
  end
  def destroy
    @sport = Sport.find(params[:id])
    # TODO Tom  存在性的check

    if @sport.destroy
      redirect_to new_admin_master_sport_path, notice: I18n.t("activemodel.success.destroy", model: Sport.model_name.human)
    else
      flash[:alert] = I18n.t("activemodel.errors.destroy", model: Sport.model_name.human)
      render :show
    end
  end
end

app/controllers/user/master/court_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class User::Master::CourtReportsController < User::UserBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  before_filter :set_current_user
  def index
    @court_report = CourtReport.new(params[:court_report])
    @court_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @court_report.assets.page(params[:page])
  end
end

app/controllers/user/master/game_reports_controller.rb
# encoding: UTF-8
#--
# FileInfo:
#   Author: Tom
#
#++
#
class User::Master::GameReportsController < User::UserBaseController
  # 对于每一个action进行权限检查
  load_and_authorize_resource 
  before_filter :set_current_user
  def index
    @game_report = GameReport.new(params[:game_report])
    @game_report.assets.per_page =  Wanerbu::Common::NUMBER_PER_PAGE
    @assets = @game_report.assets.page(params[:page])
  end
end

app/helpers/admin/master/admin_reports_helper.rb
module Admin::Master::AdminReportsHelper
end

app/helpers/admin/master/admins_helper.rb
module Admin::Master::AdminsHelper
end

app/helpers/admin/master/gym_reports_helper.rb
module Admin::Master::GymReportsHelper
end

app/helpers/admin/master/properties_helper.rb
module Admin::Master::PropertiesHelper
end

app/views/user/master/gyms/_areas.html.erb
<% if !areas.blank? %>
  <% if @gym == nil %>
    <%= collection_select(:gym, :area_id, areas.all, :id, :area,{:class =>"col-md-1"}) %>
  <% else %>
    <%= collection_select(:gym, :area_id, areas.all, :id, :area,{:selected => @gym.area_id},{:class =>"col-md-1"}) %>
  <% end %>
<% else %>
<% end %>

app/views/user/master/gyms/_cities.html.erb
<%= javascript_include_tag "user/master/cities.js" %>
<% if !cities.blank? %>
  <% if @gym == nil %>
    <%= collection_select(:gym, :city_id, cities.all, :id, :city,{:class =>"col-md-1"}) %>
  <% else %>
    <%= collection_select(:gym, :city_id, cities.all, :id, :city,{:selected => @gym.city_id},{:class =>"col-md-1"}) %>
  <% end %>
<% else %>
<% end %>

app/views/user/master/gyms/_form.html.erb
<%= javascript_include_tag "user/master/gyms.js" %>
<%= semantic_form_for([:user, :master, @gym], :html => { :class => 'form-horizontal',:multipart => true }) do |f| %>
    <%= f.inputs  do %>
      <%= f.input :name, :required => true, :input_html => {:readonly => (@gym.status.approved? or @gym.status.released? or @gym.status.suspended?)}%>
      <%= f.input :intro, :required => true %>
      <%= f.input :logo, :as =>:file,:required => true%>
      <%#= f.input :address, :required => true, :input_html => {:readonly => (@gym.status.approved? or @gym.status.released? or @gym.status.suspended?),:class=> ""}%>
     <li id="gym_province_id_input" class="select input required">
       <label class=" label" for="gym_province_id">
        <%= Gym.human_attribute_name(:address) %><abbr title="required">*</abbr>
       </label>
       <%= collection_select(:gym, :province_id, Province.all, :id, :province,{:prompt=>true},{:class =>"col-md-1"}) %>
       <span id="cities">
       </span>  
       <span id="areas">
       </span>
       <%= text_field_tag 'gym[address]', @gym.address %>  
     </li>
      <%= f.input :telephone, :required => true %>
      <input id="gym_open_time_1i" type="hidden" value="2001" name="gym[open_time(1i)]">
      <input id="gym_open_time_2i" type="hidden" value="01" name="gym[open_time(2i)]">
      <input id="gym_open_time_3i" type="hidden" value="01" name="gym[open_time(3i)]">
      <%= f.input :open_time, :as => :time_select,:ignore_date => true,:required => true,:input_html => { :class => "" } %>
      <input id="gym_close_time_1i" type="hidden" value="2001" name="gym[close_time(1i)]">
      <input id="gym_close_time_2i" type="hidden" value="01" name="gym[close_time(2i)]">
      <input id="gym_close_time_3i" type="hidden" value="01" name="gym[close_time(3i)]">
      <%= f.input :close_time, :as => :time_select,:ignore_date => true,:required => true,:input_html => { :class => "" } %>
    <% end -%>
    <%= f.actions do %>
      <%= f.action :submit, :button_html => { :class => "btn btn-primary" }, :as => :button %>
      <%= f.action :cancel, :as => :link %>
    <% end -%>
  <% end %>

app/views/user/master/gyms/_sub_menu_new.html.erb
  <ul class="nav nav-tabs">
    <li class="<%= 'active' if active_path.present? && active_path == new_user_master_gym_path %>">
      <%= link_to t('user.nav.main_menu.common.new', model: Gym.model_name.human), new_user_master_gym_path %>
    </li>

app/views/user/master/gyms/_sub_menu_start.html.erb
  <ul class="nav nav-tabs">
    <li class="<%= 'active' if active_path.present? && active_path == user_master_gyms_path %>">
      <%= link_to t('user.nav.main_menu.common.my', model: Gym.model_name.human), user_master_gyms_path %>
    </li>

app/views/user/master/gyms/edit.html.erb
<% content_for :sub_menu do %>
  <%= render :partial => 'user/master/gyms/sub_menu_start', :locals => {:active_path => nil } -%>
    <li class="active">
      <%= link_to t('user.nav.main_menu.common.edit', model: Gym.model_name.human), edit_user_master_gym_path %>
    </li>
  <%= render 'common_parts/sub_menu_end' -%>
<% end %>
<%= render 'form' %>

app/views/user/master/gyms/index.html.erb
<% content_for :sub_menu do %>
  <%= render :partial => 'user/master/gyms/sub_menu_start', :locals => {:active_path => nil } -%>
  <%= render 'common_parts/sub_menu_end' -%>
<% end %>

<div class='wb-content-sub-title'>
  <div>
    <% if can? :edit, @gym%>
      <%= link_to t('views.defaults.actions.edit'), edit_user_master_gym_path(@gym), {class: "btn btn-primary"} %>
    <%end%>
    <% if can? :apply, @gym%>
      <%= link_to t('views.defaults.actions.apply'), apply_user_master_gym_path(@gym), {method: :post, class: "btn btn-primary"} %>
    <%end%>
    <% if can? :cancel, @gym%>
      <%= link_to t('views.defaults.actions.cancel'), cancel_user_master_gym_path(@gym), {method: :post, class: "btn btn-primary"} %>
    <%end%>
    <% if can? :release, @gym%>
      <%= link_to t('views.defaults.actions.release'), release_user_master_gym_path(@gym), {method: :post, class: "btn btn-primary"} %>
    <%end%>
    <% if can? :suspend, @gym%>
      <%= link_to t('views.defaults.actions.suspend'), suspend_user_master_gym_path(@gym), {method: :post, class: "btn btn-primary"} %>
    <%end%>
    <button type="button" data-toggle="modal"class= "btn btn-primary" data-target="#uploadImageModal"><%= t('views.defaults.actions.upload_image')%></button>
  </div>
  <div class='wb-clear-both'></div>
</div>
<%= render 'common_parts/gym_show' -%>
<!-- upload image Modal -->
<div id="uploadImageModal" class="modal  fade" tabindex="-1" role="dialog" aria-labelledby="uploadImageModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="uploadImageModalLabel"><%=t('views.defaults.actions.upload_image') %></h3>
      </div>
      <%= form_tag({:controller => "gyms", :action => "upload_image"}, {:method => "post", multipart: true}) do %>
        <div class="modal-body">
          <%= hidden_field_tag 'gym_image[gym_id]', @gym.id %>
          <%= file_field_tag 'gym_image[image]' %>
          <%= text_field_tag 'gym_image[intro]' %>
        </div>
        <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal" aria-hidden="true"><%= t('views.defaults.actions.cancel') %></button>
          <%= submit_tag(t('views.defaults.actions.upload_image')) %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  <% end %>
</div>

app/views/user/master/gyms/new.html.erb
<% content_for :sub_menu do %>
  <%= render :partial => 'user/master/gyms/sub_menu_new', :locals => {:active_path => nil } -%>
  <%= render 'common_parts/sub_menu_end' -%>
<% end %>
<%= render 'form' %>