config/routes.rb
Wanerbu::Application.routes.draw do

  get "gym/gym_home"
  match 'gym/search/:sportid/:areaid/:keyword/:reservekey/:sortkey' => 'gym#search',:via=>:get
  match 'gym/one_gym/:id/:sportid' => 'gym#one_gym',:via=>:get
  match 'gym/submit_comment' => 'gym#submit_comment',:via => :post
  match 'gym/search_comment/:gymid' => 'gym#search_comment',:via=>:get
  match 'gym/delete_comment/:gymid/:commentid' => 'gym#delete_comment',:via=>:get
  match 'gym/check_comment_time' => 'gym#check_comment_time',:via => :post
  match 'gym/getcourt/:gymid/:sportid/:reservationtype' => 'gym#getcourt',:via=>:get
  match 'gym/reserve/:id/:date' => 'gym#reserve',:via=>:get
  match 'gym/searchgame/:id/:date' => 'gym#searchgame',:via=>:get
  match 'gym/check_order' => 'gym#check_order',:via => :post
  match 'gym/check_code_image/:type_code' => 'gym#check_code_image',:via => :get
  match 'gym/submit_order' => 'gym#submit_order',:via => :post
  match 'gym/search_map' => 'gym#search_map',:via => :post
  match 'gym/code_image' => 'gym#code_image',:via => :get

  get "activities/activity_home"
  get "activities/search/:id/:type" => 'activities#search',:via=>:get
  match 'activities/get_cities_by_province_id/:province_id' => 'activities#get_cities_by_province_id',:via=>:get
  match 'activities/get_areas_by_city_id/:city_id' => 'activities#get_areas_by_city_id',:via=>:get
  resources :activities, :except => [:index] 

  devise_for :users,
    :controllers => {:sessions => 'user/users/sessions', :registrations => 'user/users/registrations'},
    :path => 'auth',
    :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  devise_for :admins,
    :controllers => {:sessions => 'admin/admins/sessions'},
    :path => 'admin/auth',
    :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  root :to => 'welcome#index'

  namespace :admin do
    root :to => 'dashboard#index'
    get 'dashboard' => 'dashboard#index'
    namespace :master do
      resources :admins, :except => [:index] do
        member do
          post :lock
        end
      end
      resources :admin_reports, :only => [:index]
      resources :roles, :except => [:index]
      resources :role_reports, :only => [:index]
      resources :properties, :except => [:index]
      resources :property_reports, :only => [:index]
      resources :sports, :except => [:index]
      resources :sport_reports, :only => [:index]
      resources :gym_reports, :only => [:index,:show] do
        member do
          post :approve
          post :reject
          post :lock
          post :destroy
        end
      end
    end
  end

  namespace :user do
    root :to => 'dashboard#index'
    get 'dashboard' => 'dashboard#index'
    namespace :master do
      resources :gyms do
        member do
          post :apply
          post :cancel
          post :release
          post :suspend
        end
      end
      match 'gyms/upload_image' => 'gyms#upload_image',:via => :post
      match 'gyms/remove_image' => 'gyms#remove_image',:via => :post
      match 'gyms/get_cities_by_province_id/:province_id' => 'gyms#get_cities_by_province_id',:via=>:get
      match 'gyms/:id/get_cities_by_province_id/:province_id' => 'gyms#get_cities_by_province_id',:via=>:get
      match 'gyms/get_areas_by_city_id/:city_id' => 'gyms#get_areas_by_city_id',:via=>:get
      match 'gyms/:id/get_areas_by_city_id/:city_id' => 'gyms#get_areas_by_city_id',:via=>:get
      resources :courts, :except => [:index]
      resources :court_reports, :only => [:index]
      match 'courts/edit_court_properties_select/:sport_id' => 'courts#edit_court_properties_select',:via=>:get
      match 'courts/:id/edit_court_properties_select/:sport_id' => 'courts#edit_court_properties_select',:via=>:get
      resources :games, :except => [:index] do
        member do
          post :new_price_rule
          post :new_reservation_rule
        end
      end
      match 'games/delete_game_price_rule/:price_rule_id' => 'games#delete_game_price_rule',:via=>:get
      match 'games/delete_game_reservation_rule/:reservation_rule_id' => 'games#delete_game_reservation_rule',:via=>:get
      resources :game_reports, :only => [:index]
    end
  end

end

app/views/layouts/admin/_info_or_error_msg.html.erb
              <% if flash.present? %>
                <% if flash[:notice].present? %>
                  <div class="alert alert-success"><%= flash[:notice] %></div>
                <% end %>
                <% if flash[:alert].present? %>
                  <div class="alert alert-danger"><%= flash[:alert] %></div>
                <% end %>
                <% flash.clear %>
              <% end %>

app/views/layouts/admin/_left_nav.html.erb
          <div class="well sidebar-nav">
            <%= render_navigation(:level => :all, :expand_all => true, :context => :admin) %>
          </div>

app/views/layouts/admin/_top_fixed_nav.html.erb
      <!-- Fixed navbar -->
      <div class="navbar navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">玩儿不后台管理</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to t('admin.nav.main_menu.dashboard'), admin_dashboard_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <div class="btn-group" style="margin-top:8px;">
                  <a class="btn btn-primary" href="#"><i class="glyphicon glyphicon-user glyphicon-white"></i>&nbsp;&nbsp;<%= current_admin.login_id %></a>
                  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to '#' do %>
                        <i class="glyphicon glyphicon-pencil"></i>&nbsp;&nbsp;编辑个人信息
                      <% end %>
                    </li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to destroy_admin_session_path, {method: :DELETE} do %>
                        <i class="glyphicon glyphicon-trash"></i>&nbsp;&nbsp;退出账户
                      <% end %>
                    </li>
                  </ul>
                </div>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

app/views/layouts/admin/admin_base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>玩儿不</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="玩儿不">
    <meta name="author" content="wanerbu">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "admin", :media => "all" %>
    <%= yield :head_stylesheet %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "admin/admin_base" %>
    <%= yield :head_javascript %>
    
    <!-- TODO dairg 需要调查清楚这里的作用 -->
    <%= csrf_meta_tags %>
    

    <!-- TODO dairg 需要调查清楚这里的作用 -->
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- TODO dairg 需要调查清楚这里的作用 -->
    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <!-- 顶部的固定导航 -->
      <%= render 'layouts/admin/top_fixed_nav' -%>
    </div>
    <div>
      <div class="container">
        <div class="row">
          <div class="col-md-2">
            <!-- 左边的主菜单 -->
            <%= render 'layouts/admin/left_nav' -%>
          </div>
          <div class="col-md-10">
            <div class="col-md-12">
              <!-- 主工作区的顶部菜单 -->
              <%= yield :sub_menu -%>
            </div>
            <div id='main-content' class="col-md-12">

              <!-- 提示信息或者错误信息 -->
              <%= render 'layouts/admin/info_or_error_msg' -%>

              <!-- 主工作区内容 -->
              <%= yield %>
            </div>
          </div>
        </div><!--/row-->

      </div><!--/.container-->
      <br>
      <div class="container">
        <!-- 页脚 -->
        <%= render 'layouts/admin/footer' -%>
      </div>
    </div>


  </body>
</html>

app/views/layouts/admin/admin_devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>玩儿不</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="玩儿不">
    <meta name="author" content="wanerbu">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    
  </head>

  <body>

    <div class="container">

      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>


    </div> <!-- /container -->

  </body>
</html>